# Generated by Django 6.0.1 on 2026-01-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='investment_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='startup_info',
            field=models.TextField(blank=True),
        ),
    ]
